alias www="cd /Users/jschein/public_html/"
alias mvim="/Applications/mvim"
alias apache_restart="sudo /Applications/MAMP/bin/apache2/bin/apachectl restart"
alias vhosts="cd /Applications/MAMP/conf/apache/extra/vhosts"
alias mamp="cd /Applications/MAMP/"
